---
- name: Installing sql database
  hosts: mysql
  become: true
  tasks:
  - name: installig mysql sever
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: starting and enabling
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: Install Python3 and pip
    ansible.builtin.yum:
      name:
        - python3
        - python3-pip
      state: present

  - name: Install PyMySQL
    ansible.builtin.pip:
      name: PyMySQL

  - name: Set root password (local)
    community.mysql.mysql_user:
      name: root
      host: localhost
      password: "RoboShop@1"
      login_unix_socket: /var/lib/mysql/mysql.sock
      check_implicit_admin: true
      state: present
