- name: Create DB user for remote imports
  hosts: mysql
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install PyMySQL (needed for community.mysql modules)
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3

    - name: Create roboshop user allowed from VPC
      community.mysql.mysql_user:
        name: roboshop
        password: "RoboShop@1"
        host: "172.31.%"
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_password: "RoboShop@1"
