---
- name: shipping
  hosts: shipping
  become: true
  tasks:
  - name: installing maven
    ansible.builtin.dnf:
      name: maven 
      state: present

  - name: Create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      home: /app
      shell: /sbin/nologin
      system: true
      create_home: true
      state: present


  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unzipping the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: true

  - name: Installling dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: renaming jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args: 
      chdir: /app

  - name: copying shipping repo
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
      
  - name: daemon reloading 
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting and enabling shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: true

  - name: Installing mysql
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: loading schema
    anisble.builtin.shell: mysql -h mysql.chainverse.online -uroot -pRoboShop@1 < /app/db/schema.sql

  - name: loading user data
    ansible.buitlin.shell: mysql -h mysql.chainverse.online -uroot -pRoboShop@1 < /app/db/app-user.sql 

  - name: loading data
    ansible.builtin.shell: mysql -h mysql.chainverse.online -uroot -pRoboShop@1 < /app/db/master-data.sql

  - name: restarting shipping
    ansible.builtin.servicea:
      name: shipping
      state: restarted
