---
- name: shipping
  hosts: shipping
  become: true
  vars:
    mysql_password: RoboShop@1
  tasks:
  - name: installing maven
    ansible.builtin.dnf:
      name: maven 
      state: present

  - name: Create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      home: /app
      shell: /sbin/nologin
      system: true
      create_home: true
      state: present


  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unzipping the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: true

  - name: Installling dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: renaming jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args: 
      chdir: /app

  - name: copying shipping repo
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
      
  - name: daemon reloading 
    ansible.builtin.systemd_service:
      daemon_reload: true


  - name: Installing mysql
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: check cities schema exists or not
    ansible.builtin.command:  mysql -h mysql.chainverse.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "schema output: {{schema}}"

  - name: load cities data
    ansible.builtin.shell: "mysql -h mysql.chainverse.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
    when: schema.stdout != "1"

  - name: start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
